<a href="https://colab.research.google.com/github/SPageot/pytorch-test/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

List

In [6]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.875986  , 0.26480861, 0.80446628, 0.82052161],
       [0.33940363, 0.16331828, 0.38557461, 0.88833706],
       [0.45501816, 0.01293394, 0.93933756, 0.82523965]])

In [8]:
np1.dtype

dtype('float64')

Tensor

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.7575,  0.0525,  0.4625, -1.6630],
        [ 0.6987, -0.9893,  0.7567, -1.5420],
        [-0.4351, -0.2284, -0.8138, -0.3112]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8760, 0.2648, 0.8045, 0.8205],
        [0.3394, 0.1633, 0.3856, 0.8883],
        [0.4550, 0.0129, 0.9393, 0.8252]], dtype=torch.float64)

Tensor Range


In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor Reshape

In [17]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

Tensor View

In [26]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
my_torch5[1] = 13
my_torch5

tensor([ 0, 13,  2,  3,  4,  5,  6,  7,  8,  9])

In [34]:
my_torch6

tensor([[ 0, 13,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

Simple Neural Network

In [ ]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

